"""Deterministic test-slice evaluation of frozen controllers in calibration worlds.

Experiment A (closed-policy zero-shot): the saved policy acts on observations
generated by the world (its prev-Q / prev-SEC features change with the
surrogate), parameters frozen, deterministic actions, reset(seed=42).

Experiment B (fixed-action counterfactual replay): the (T, K) requested-action
trajectory recorded for the same checkpoint in the pinned world (Experiment A,
tag given by --pinned-tag) is replayed unchanged; only the scoring changes.

Environment, traffic, reward, switching model and reset are exactly those of
the paper's evaluator (research/phase7/evaluate_multiseed.py); only
paths_cfg.profiling_twin.{models,manifest} change between worlds.

--twin v030 prepends the vendored UPF_NDT v0.3.0 package to sys.path and uses
the pre-fix switching_costs.yaml (profiling thesis-v1.1). It exists only to
reproduce the manuscript's Table I, which predates twin v0.4.0.

Examples
  python evaluate_worlds.py --tag main --worlds pinned --exp A
  python evaluate_worlds.py --tag main --worlds primary secondary --exp A B
  python evaluate_worlds.py --tag table1_v030 --twin v030 --pool search --worlds pinned --exp A --no-steps
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import warnings
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

warnings.filterwarnings("ignore")
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))


def _early_twin_switch(argv):
    """Must run before anything imports upf_digital_twin (workers are forked)."""
    if "--twin" in argv and argv[argv.index("--twin") + 1] == "v030":
        sys.path.insert(0, str(HERE / "vendor" / "upf_digital_twin_v0.3.0"))
        os.environ["PYTHONPATH"] = str(HERE / "vendor" / "upf_digital_twin_v0.3.0") + os.pathsep + os.environ.get("PYTHONPATH", "")


_early_twin_switch(sys.argv)

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

import rb_common as C  # noqa: E402


def safe(s: str) -> str:
    return s.replace("|", "__").replace("/", "-").replace(" ", "_").replace("(", "").replace(")", "").replace(",", "").replace("=", "")


def search_extras() -> list[dict]:
    """Candidates used ONLY for the Table-I traceability search (twin v0.3.0)."""
    out = []
    for pat in ("mappo_pool_off_seed*", "mappo_budget_off_seed*", "mappo_lambda_sw_4_seed*"):
        for d in sorted(C.EXP.glob(pat)):
            p = d / "mappo_best.pt"
            if p.exists():
                out.append(dict(ckpt_id=f"MAPPO|{d.name}/mappo_best.pt", family="MAPPO", kind="mappo",
                                seed=int(d.name.split("seed")[1].split("_")[0]), path=str(p),
                                source="search-only (scenario-variant sweep dir)", cohorts=["search"]))
    for r in C.checkpoint_registry():
        if r["kind"] == "mappo" and r["family"] == "MAPPO":
            p = Path(r["path"]).with_name("mappo_final.pt")
            if p.exists():
                out.append(dict(r, ckpt_id=f"MAPPO|{p.relative_to(C.EXP).as_posix()}", path=str(p),
                                source="search-only (final, not best-of-validation)", cohorts=["search"]))
        if r["kind"] == "central":
            for name in ("ppo_multi_site_final.zip", "best_model.zip"):
                p = Path(r["path"]).with_name(name)
                if p.exists() and p != Path(r["path"]):
                    out.append(dict(r, ckpt_id=f"Centralized PPO|{p.relative_to(C.EXP).as_posix()}", path=str(p),
                                    source=f"search-only ({name})", cohorts=["search"]))
    return out


def entries_for(pool: str) -> list[dict]:
    reg = C.checkpoint_registry()
    ents = reg + [dict(b, path="-", source="baseline", cohorts=["baseline"]) for b in C.BASELINES]
    if pool == "search":
        ents += search_extras()
    return ents


def run_chunk(tag: str, twin: str, world_name: str, exp: str, entries: list[dict], pinned_tag: str,
              save_steps: bool) -> list[dict]:
    C.set_threads()
    if twin == "v030":
        import upf_digital_twin
        assert "vendor" in upf_digital_twin.__file__, upf_digital_twin.__file__
    world = C.world_by_name(world_name)
    sc = C.SWITCH_V11 if twin == "v030" else None
    t0 = time.time()
    env = C.build_env(world, switching_costs=sc)
    t_env = time.time() - t0
    delay_budget, max_loss = C.qos_budget()
    outdir = C.ROLLOUTS / tag / world_name / exp
    outdir.mkdir(parents=True, exist_ok=True)
    rows = []
    for e in entries:
        t1 = time.time()
        if exp == "A":
            pol, reset_fn = C.make_policy(e)
            ep = C.run_episode(env, policy=pol, reset_fn=reset_fn)
        else:
            src = C.ROLLOUTS / pinned_tag / "pinned" / "A" / f"{safe(e['ckpt_id'])}.npz"
            acts = np.load(src)["action"]
            ep = C.run_episode(env, replay_actions=acts)
        meta = dict(tag=tag, twin=twin, world=world_name, experiment=exp, ckpt_id=e["ckpt_id"],
                    family=e["family"], seed=e["seed"], path=e.get("path", "-"))
        if save_steps:
            C.save_episode(outdir / f"{safe(e['ckpt_id'])}.npz", ep, meta)
        for m in C.episode_metrics(ep, delay_budget, max_loss):
            rows.append(dict(tag=tag, twin=twin, world=world_name, tier=world["tier"], protocol=world["protocol"],
                             config=world["config"], fold=world["fold"], experiment=exp,
                             ckpt_id=e["ckpt_id"], family=e["family"], seed=e["seed"],
                             cohorts="+".join(e["cohorts"]), source=e["source"], **m,
                             seconds=round(time.time() - t1 + t_env / max(1, len(entries)), 2)))
    return rows


def chunks(entries):
    heavy = [e for e in entries if e["kind"] == "ippo"]
    light = [e for e in entries if e["kind"] != "ippo"]
    out = [heavy[i:i + 2] for i in range(0, len(heavy), 2)]
    out += [light[i:i + 10] for i in range(0, len(light), 10)]
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", required=True)
    ap.add_argument("--twin", choices=["v040", "v030"], default="v040")
    ap.add_argument("--pool", choices=["registry", "search"], default="registry")
    ap.add_argument("--worlds", nargs="+", default=["pinned"],
                    help="world names, or tiers: reference primary secondary")
    ap.add_argument("--exp", nargs="+", choices=["A", "B"], default=["A"])
    ap.add_argument("--families", nargs="*", default=None, help="restrict to these families (smoke tests)")
    ap.add_argument("--seeds", nargs="*", type=int, default=None)
    ap.add_argument("--cohorts", nargs="*", default=None, help="restrict to checkpoints in any of these cohorts")
    ap.add_argument("--pinned-tag", default="main")
    ap.add_argument("--workers", type=int, default=30)
    ap.add_argument("--no-steps", action="store_true")
    args = ap.parse_args()
    os.environ["OMP_NUM_THREADS"] = "1"

    wnames = []
    for w in args.worlds:
        if w in ("reference", "primary", "secondary"):
            wnames += [x["world"] for x in C.worlds((w,))]
        else:
            wnames.append(C.world_by_name(w)["world"])
    ents = entries_for(args.pool)
    if args.families:
        ents = [e for e in ents if e["family"] in args.families]
    if args.seeds:
        ents = [e for e in ents if e["seed"] in args.seeds]
    if args.cohorts:
        ents = [e for e in ents if set(e["cohorts"]) & set(args.cohorts)]
    resdir = HERE / "results" / args.tag
    resdir.mkdir(parents=True, exist_ok=True)
    t0 = time.time()
    for x in sorted(args.exp):                      # A before B: B replays A's pinned actions
        jobs = [(args.tag, args.twin, w, x, ch, args.pinned_tag, not args.no_steps)
                for w in wnames for ch in chunks(ents)]
        print(f"exp {x}: {len(ents)} controllers x {len(wnames)} worlds = {len(ents) * len(wnames)} episodes "
              f"in {len(jobs)} jobs", flush=True)
        done = {}
        with ProcessPoolExecutor(max_workers=args.workers) as pool:
            futs = {pool.submit(run_chunk, *j): j for j in jobs}
            for i, f in enumerate(as_completed(futs), 1):
                j = futs[f]
                done.setdefault(j[2], []).extend(f.result())
                if i % max(1, len(jobs) // 10) == 0 or i == len(jobs):
                    print(f"  {i}/{len(jobs)} jobs, {time.time() - t0:7.0f}s", flush=True)
        for w, rows in done.items():
            f = resdir / f"{w}__{x}.csv"
            df = pd.DataFrame(rows)
            if f.exists():                            # merge: new rows replace same checkpoint/cluster
                old = pd.read_csv(f)
                old = old[~old.ckpt_id.isin(set(df.ckpt_id))]
                df = pd.concat([old, df], ignore_index=True)
            df.to_csv(f, index=False)
    if not args.no_steps and "pinned" in wnames and "A" in args.exp:
        env = C.build_env(C.world_by_name("pinned"))
        ep = C.run_episode(env, policy=C.make_policy(C.BASELINES[1])[0])
        np.savez_compressed(C.ROLLOUTS / args.tag / "traffic_test.npz", load_gbps=ep["load"], forecast_gbps=ep["forecast"])
    print(f"done in {time.time() - t0:.0f}s", flush=True)


if __name__ == "__main__":
    main()
